'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace LampCommon
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampCredentials", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Partial Public Class LampCredentials
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private PasswordField As String
        
        Private UsernameField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                Me.PasswordField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                Me.UsernameField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampUserWrapper", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Partial Public Class LampUserWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private statusField As LampCommon.LampStatus
        
        Private userField As LampCommon.LampUser
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property status() As LampCommon.LampStatus
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property user() As LampCommon.LampUser
            Get
                Return Me.userField
            End Get
            Set
                Me.userField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampUser", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Partial Public Class LampUser
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private EmailField As String
        
        Private NameField As String
        
        Private PasswordField As String
        
        Private PermissionLevelField As LampCommon.UserPermission
        
        Private UserIdField As String
        
        Private UsernameField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                Me.EmailField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                Me.NameField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                Me.PasswordField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PermissionLevel() As LampCommon.UserPermission
            Get
                Return Me.PermissionLevelField
            End Get
            Set
                Me.PermissionLevelField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UserId() As String
            Get
                Return Me.UserIdField
            End Get
            Set
                Me.UserIdField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Username() As String
            Get
                Return Me.UsernameField
            End Get
            Set
                Me.UsernameField = value
            End Set
        End Property
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.FlagsAttribute(),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampStatus", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Public Enum LampStatus As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        OK = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NoAccess = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        DoesNotExist = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InvalidUsernameOrPassword = 4
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        InternalServerError = 8
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        GuidConflict = 16
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="UserPermission", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Public Enum UserPermission As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Guest = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Standard = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Elevated = 2
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Admin = 3
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampTemplate", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Partial Public Class LampTemplate
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private BaseDrawingField As LampCommon.LampDxfDocument
        
        Private GUIDField As String
        
        Private HeightField As Double
        
        Private IsCompleteField As Boolean
        
        Private LengthField As Double
        
        Private LongDescriptionField As String
        
        Private MaterialField As String
        
        Private MaterialThicknessField As Double
        
        Private NameField As String
        
        Private ShortDescriptionField As String
        
        Private SubmitDateField As System.Nullable(Of Date)
        
        Private TagsField() As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BaseDrawing() As LampCommon.LampDxfDocument
            Get
                Return Me.BaseDrawingField
            End Get
            Set
                Me.BaseDrawingField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GUID() As String
            Get
                Return Me.GUIDField
            End Get
            Set
                Me.GUIDField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Height() As Double
            Get
                Return Me.HeightField
            End Get
            Set
                Me.HeightField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IsComplete() As Boolean
            Get
                Return Me.IsCompleteField
            End Get
            Set
                Me.IsCompleteField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Length() As Double
            Get
                Return Me.LengthField
            End Get
            Set
                Me.LengthField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property LongDescription() As String
            Get
                Return Me.LongDescriptionField
            End Get
            Set
                Me.LongDescriptionField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Material() As String
            Get
                Return Me.MaterialField
            End Get
            Set
                Me.MaterialField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MaterialThickness() As Double
            Get
                Return Me.MaterialThicknessField
            End Get
            Set
                Me.MaterialThicknessField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                Me.NameField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ShortDescription() As String
            Get
                Return Me.ShortDescriptionField
            End Get
            Set
                Me.ShortDescriptionField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SubmitDate() As System.Nullable(Of Date)
            Get
                Return Me.SubmitDateField
            End Get
            Set
                Me.SubmitDateField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Tags() As String()
            Get
                Return Me.TagsField
            End Get
            Set
                Me.TagsField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampDxfDocument", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Partial Public Class LampDxfDocument
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private BottomLeftField As netDxf.Vector3
        
        Private SerializedDrawingField As String
        
        Private TopRightField As netDxf.Vector3
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property BottomLeft() As netDxf.Vector3
            Get
                Return Me.BottomLeftField
            End Get
            Set
                Me.BottomLeftField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SerializedDrawing() As String
            Get
                Return Me.SerializedDrawingField
            End Get
            Set
                Me.SerializedDrawingField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TopRight() As netDxf.Vector3
            Get
                Return Me.TopRightField
            End Get
            Set
                Me.TopRightField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampJob", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Partial Public Class LampJob
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="LampTemplateWrapper", [Namespace]:="http://schemas.datacontract.org/2004/07/LampCommon")>  _
    Partial Public Class LampTemplateWrapper
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private StatusField As LampCommon.LampStatus
        
        Private TemplateField As LampCommon.LampTemplate
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Status() As LampCommon.LampStatus
            Get
                Return Me.StatusField
            End Get
            Set
                Me.StatusField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Template() As LampCommon.LampTemplate
            Get
                Return Me.TemplateField
            End Get
            Set
                Me.TemplateField = value
            End Set
        End Property
    End Class
End Namespace

Namespace netDxf
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Vector3", [Namespace]:="http://schemas.datacontract.org/2004/07/netDxf")>  _
    Partial Public Structure Vector3
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private XField As Double
        
        Private YField As Double
        
        Private ZField As Double
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property X() As Double
            Get
                Return Me.XField
            End Get
            Set
                Me.XField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Y() As Double
            Get
                Return Me.YField
            End Get
            Set
                Me.YField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Z() As Double
            Get
                Return Me.ZField
            End Get
            Set
                Me.ZField = value
            End Set
        End Property
    End Structure
End Namespace


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ILampService")>  _
Public Interface ILampService
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/Authenticate", ReplyAction:="http://tempuri.org/ILampService/AuthenticateResponse")>  _
    Function Authenticate(ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampUserWrapper

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/Authenticate", ReplyAction:="http://tempuri.org/ILampService/AuthenticateResponse")>
    Function AuthenticateAsync(ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampUserWrapper)

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/AddTemplate", ReplyAction:="http://tempuri.org/ILampService/AddTemplateResponse")>
    Function AddTemplate(ByVal template As LampCommon.LampTemplate, ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampStatus

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/AddTemplate", ReplyAction:="http://tempuri.org/ILampService/AddTemplateResponse")>
    Function AddTemplateAsync(ByVal template As LampCommon.LampTemplate, ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampStatus)

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/QueueJob", ReplyAction:="http://tempuri.org/ILampService/QueueJobResponse")>
    Function QueueJob(ByVal job As LampCommon.LampJob, ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampStatus

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/QueueJob", ReplyAction:="http://tempuri.org/ILampService/QueueJobResponse")>
    Function QueueJobAsync(ByVal job As LampCommon.LampJob, ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampStatus)

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/GetTemplate", ReplyAction:="http://tempuri.org/ILampService/GetTemplateResponse")>
    Function GetTemplate(ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampTemplateWrapper

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/GetTemplate", ReplyAction:="http://tempuri.org/ILampService/GetTemplateResponse")>
    Function GetTemplateAsync(ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampTemplateWrapper)

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/GetAllTemplate", ReplyAction:="http://tempuri.org/ILampService/GetAllTemplateResponse")>
    Function GetAllTemplate(ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampTemplate()

    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ILampService/GetAllTemplate", ReplyAction:="http://tempuri.org/ILampService/GetAllTemplateResponse")>
    Function GetAllTemplateAsync(ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampTemplate())
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Public Interface ILampServiceChannel
    Inherits ILampService, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>
Partial Public Class LampServiceClient
    Inherits System.ServiceModel.ClientBase(Of ILampService)
    Implements ILampService

    Public Sub New()
        MyBase.New
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub

    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub

    Public Function Authenticate(ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampUserWrapper Implements ILampService.Authenticate
        Return MyBase.Channel.Authenticate(credentials)
    End Function

    Public Function AuthenticateAsync(ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampUserWrapper) Implements ILampService.AuthenticateAsync
        Return MyBase.Channel.AuthenticateAsync(credentials)
    End Function

    Public Function AddTemplate(ByVal template As LampCommon.LampTemplate, ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampStatus Implements ILampService.AddTemplate
        Return MyBase.Channel.AddTemplate(template, credentials)
    End Function

    Public Function AddTemplateAsync(ByVal template As LampCommon.LampTemplate, ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampStatus) Implements ILampService.AddTemplateAsync
        Return MyBase.Channel.AddTemplateAsync(template, credentials)
    End Function

    Public Function QueueJob(ByVal job As LampCommon.LampJob, ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampStatus Implements ILampService.QueueJob
        Return MyBase.Channel.QueueJob(job, credentials)
    End Function

    Public Function QueueJobAsync(ByVal job As LampCommon.LampJob, ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampStatus) Implements ILampService.QueueJobAsync
        Return MyBase.Channel.QueueJobAsync(job, credentials)
    End Function

    Public Function GetTemplate(ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampTemplateWrapper Implements ILampService.GetTemplate
        Return MyBase.Channel.GetTemplate(credentials)
    End Function

    Public Function GetTemplateAsync(ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampTemplateWrapper) Implements ILampService.GetTemplateAsync
        Return MyBase.Channel.GetTemplateAsync(credentials)
    End Function

    Public Function GetAllTemplate(ByVal credentials As LampCommon.LampCredentials) As LampCommon.LampTemplate() Implements ILampService.GetAllTemplate
        Return MyBase.Channel.GetAllTemplate(credentials)
    End Function

    Public Function GetAllTemplateAsync(ByVal credentials As LampCommon.LampCredentials) As System.Threading.Tasks.Task(Of LampCommon.LampTemplate()) Implements ILampService.GetAllTemplateAsync
        Return MyBase.Channel.GetAllTemplateAsync(credentials)
    End Function
End Class
